"""§24.1 gateway HMAC verifier tests.

Two layers:

1. Pure-function / dependency tests (no Redis) — valid tuple passes, every
   tamper variant returns 401, dev short-circuit passes. These mount the real
   ``verify_gateway_hmac`` dependency on a throwaway FastAPI route and drive it
   through Starlette's TestClient so the body-reading path is exercised end to
   end.

2. Nonce/replay tests — spin a REAL Redis via testcontainers-python and assert a
   replayed ``X-Request-ID`` is rejected. Skipped (not silently passed) when
   Docker is unavailable.

The expected-signature helper here is an INDEPENDENT reimplementation of the
canonical string (it does NOT call the production ``compute_gateway_signature``)
so "valid → passes" is not a tautology. In addition, ``test_go_cross_check_vector``
pins two signatures generated by the Go signer itself, proving byte-for-byte
agreement across languages.
"""

from __future__ import annotations

import collections.abc as cabc
import hashlib
import hmac
import time

import pytest
from fastapi import Depends, FastAPI
from fastapi.testclient import TestClient

from avatar.api.security import GATEWAY_BODY_LIMIT, verify_gateway_hmac
from avatar.config import get_settings

# 32-char placeholder HMAC secret — test only, NOT a real secret. Matches the Go
# test ``testSecret`` so the cross-check vectors below line up.
TEST_SECRET = "0123456789abcdef0123456789abcdef"

# Fixed identity tuple shared across the table.
FIX_USER_ID = "11111111-1111-1111-1111-111111111111"
FIX_KYC_TIER = "2"
FIX_ACCOUNT_TYPE = "PERSONAL"
FIX_EMAIL_VERIFIED = "true"
FIX_REQUEST_ID = "req-abc"


# --- independent signer (NOT the production function) -------------------------


def _independent_sign(
    secret: str,
    method: str,
    path: str,
    body: bytes,
    *,
    user_id: str = FIX_USER_ID,
    kyc_tier: str = FIX_KYC_TIER,
    account_type: str = FIX_ACCOUNT_TYPE,
    email_verified: str = FIX_EMAIL_VERIFIED,
    request_id: str = FIX_REQUEST_ID,
    ts: str,
) -> str:
    """Independently derive the §24.1 hex signature (mirrors the Go test helper)."""
    body_hash_hex = hashlib.sha256(body).hexdigest()
    identity = "|".join([user_id, kyc_tier, account_type, email_verified, request_id, ts])
    canonical = (
        f"{len(method)}\n{method}\n"
        f"{len(path)}\n{path}\n"
        f"{len(body_hash_hex)}\n{body_hash_hex}\n"
        f"{identity}"
    )
    return hmac.new(secret.encode("utf-8"), canonical.encode("utf-8"), hashlib.sha256).hexdigest()


def _signed_headers(
    secret: str,
    method: str,
    path: str,
    body: bytes,
    ts: int,
    *,
    account_type: str = FIX_ACCOUNT_TYPE,
    request_id: str = FIX_REQUEST_ID,
) -> dict[str, str]:
    ts_str = str(ts)
    sig = _independent_sign(
        secret,
        method,
        path,
        body,
        account_type=account_type,
        request_id=request_id,
        ts=ts_str,
    )
    return {
        "X-User-Id": FIX_USER_ID,
        "X-Kyc-Tier": FIX_KYC_TIER,
        "X-Account-Type": account_type,
        "X-Email-Verified": FIX_EMAIL_VERIFIED,
        "X-Request-ID": request_id,
        "X-Gateway-Ts": ts_str,
        "X-Gateway-Signature": sig,
    }


# --- test app + settings override --------------------------------------------


def _build_client(
    monkeypatch: pytest.MonkeyPatch,
    *,
    secret: str,
    nonce_redis_url: str = "",
) -> TestClient:
    """Build a tiny app whose protected routes require verify_gateway_hmac.

    Overrides the gateway settings (conftest forces an empty secret autouse) and
    clears the settings cache so the override takes effect.
    """
    monkeypatch.setenv("GATEWAY_HMAC_SECRET", secret)
    monkeypatch.setenv("GATEWAY_NONCE_REDIS_URL", nonce_redis_url)
    get_settings.cache_clear()

    app = FastAPI()

    @app.get("/protected", dependencies=[Depends(verify_gateway_hmac)])
    async def _protected_get() -> dict[str, bool]:
        return {"ok": True}

    @app.post("/protected", dependencies=[Depends(verify_gateway_hmac)])
    async def _protected_post() -> dict[str, bool]:
        return {"ok": True}

    return TestClient(app)


# --- table: valid + every tamper variant -------------------------------------


def test_valid_get_passes(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 200, "correctly-signed GET must pass"


def test_valid_post_with_body_passes(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    body = b'{"title":"test"}'
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "POST", "/protected", body, now)
    resp = client.post("/protected", headers=headers, content=body)
    assert resp.status_code == 200, "correctly-signed POST with body must pass"


def test_tampered_hmac_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    headers["X-Gateway-Signature"] = "a" * 64  # valid hex, wrong digest
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "tampered (wrong) signature must be 401"


def test_non_hex_signature_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    headers["X-Gateway-Signature"] = "not-hex-zzzz"
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "non-hex signature must be 401"


def test_forged_kyc_tier_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    # Attacker signs over the REAL tier (2) but forges X-Kyc-Tier=3 on the wire.
    # Recomputed canonical uses the forged header → mismatch → 401. Core §24.1 threat.
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    headers["X-Kyc-Tier"] = "3"
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "forged kyc tier must be 401"


def test_tampered_body_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    body = b'{"title":"original"}'
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "POST", "/protected", body, now)
    # Send a different body than what was signed.
    resp = client.post("/protected", headers=headers, content=b'{"title":"tampered"}')
    assert resp.status_code == 401, "tampered body must be 401 (body hash bound)"


def test_stale_ts_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    stale = int(time.time()) - 30 - 5  # beyond +skew
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", stale)
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "stale ts beyond skew must be 401"


def test_future_ts_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    future = int(time.time()) + 30 + 5  # beyond -skew
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", future)
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "future ts beyond skew must be 401"


def test_non_numeric_ts_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    headers["X-Gateway-Ts"] = "not-a-number"
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "non-numeric ts must be 401"


def test_missing_signature_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    del headers["X-Gateway-Signature"]
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "missing signature must be 401"


def test_missing_ts_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now)
    del headers["X-Gateway-Ts"]
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "missing ts must be 401"


def test_wrong_secret_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    # Signed with a different secret than the verifier holds.
    headers = _signed_headers("f" * 32, "GET", "/protected", b"", now)
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "wrong-secret signature must be 401"


def test_empty_account_type_still_verifies(monkeypatch: pytest.MonkeyPatch) -> None:
    # §24.1 empty-field rule: an empty value is an empty field with stable pipe
    # positions. A request signed with account_type="" verifies when sent empty.
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now, account_type="")
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 200, "empty account type must still verify"


def test_dev_empty_secret_skips_verification(monkeypatch: pytest.MonkeyPatch) -> None:
    # Dev posture: empty secret → passthrough. Unsigned request must pass.
    client = _build_client(monkeypatch, secret="")
    resp = client.get("/protected")
    assert resp.status_code == 200, "dev-no-secret must skip verification"


def test_cross_endpoint_replay_rejected_401(monkeypatch: pytest.MonkeyPatch) -> None:
    # A signature over POST /protected with one body must not verify on a
    # different path. Here we sign over a body+path and resend the signature on a
    # request whose body differs → path/body binding rejects it.
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    body = b'{"amount":100}'
    headers = _signed_headers(TEST_SECRET, "POST", "/protected", body, now)
    # Reuse the signature with a different body → mismatch.
    resp = client.post("/protected", headers=headers, content=b'{"amount":999}')
    assert resp.status_code == 401, "replay with altered body must be 401"


def test_oversized_body_rejected_413(monkeypatch: pytest.MonkeyPatch) -> None:
    # A body just past GATEWAY_BODY_LIMIT must be rejected with 413 (not the
    # generic 401) and never fully buffered — mirrors the Go verifier's
    # BODY_TOO_LARGE / io.LimitReader(limit+1) path. The signature is computed
    # over the oversized body so the rejection is the size cap, not a sig
    # mismatch (the size check fires before signature verification).
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET)
    body = b"x" * (GATEWAY_BODY_LIMIT + 1)
    headers = _signed_headers(TEST_SECRET, "POST", "/protected", body, now)
    resp = client.post("/protected", headers=headers, content=body)
    assert resp.status_code == 413, "oversized body must be 413 BODY_TOO_LARGE"


# --- byte-for-byte cross-check against the Go signer -------------------------


def test_go_cross_check_vector(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin signatures the GO signer produced; assert the Python verifier accepts.

    These hex digests were generated by a standalone Go program using the SAME
    crypto/hmac + crypto/sha256 + fmt.Sprintf canonical layout as
    gateway/internal/platform/middleware/identity.go and
    user/internal/platform/middleware/gateway_signature.go. If the Python
    canonical string drifts by a single byte these fail.

    Canonical string (documented for a Go-side cross-check test):
        {len(method)}\\n{method}\\n{len(path)}\\n{path}\\n
        {len(bodyHashHex)}\\n{bodyHashHex}\\n
        {X-User-Id}|{X-Kyc-Tier}|{X-Account-Type}|{X-Email-Verified}|{rid}|{ts}

    Vector 1 (POST, JSON body):
        secret = "0123456789abcdef0123456789abcdef"
        method = "POST"   path = "/api/avatar/sessions"
        body   = {"room":"demo","identity":"u1"}
        id tuple = 11111111-1111-1111-1111-111111111111 | 2 | PERSONAL | true
                   | req-abc | 1750000000
        → 5cda5e00991d0a2ce0e849fcbbb1faf0e4a4a18ee15c82bad4c29963ef77a6ab

    Vector 2 (GET, empty body):
        method = "GET"    path = "/api/avatar/health"   body = b""
        id tuple = 11111111-... | 0 | PERSONAL | false | req-xyz | 1750000000
        → a5eeeff2a20d4b9b81bfea9a935f0c4eeae18b82a988d3e2fea46459e470ba33
    """
    monkeypatch.setenv("GATEWAY_HMAC_SECRET", TEST_SECRET)
    get_settings.cache_clear()

    from avatar.api.security import compute_gateway_signature

    # Vector 1 — POST with body.
    sig1 = compute_gateway_signature(
        TEST_SECRET.encode("utf-8"),
        method="POST",
        path="/api/avatar/sessions",
        body=b'{"room":"demo","identity":"u1"}',
        user_id="11111111-1111-1111-1111-111111111111",
        kyc_tier="2",
        account_type="PERSONAL",
        email_verified="true",
        request_id="req-abc",
        ts="1750000000",
    ).hex()
    assert sig1 == "5cda5e00991d0a2ce0e849fcbbb1faf0e4a4a18ee15c82bad4c29963ef77a6ab", (
        "Python signature must match the Go signer byte-for-byte (vector 1)"
    )

    # Vector 2 — GET, empty body, different tier/email/rid.
    sig2 = compute_gateway_signature(
        TEST_SECRET.encode("utf-8"),
        method="GET",
        path="/api/avatar/health",
        body=b"",
        user_id="11111111-1111-1111-1111-111111111111",
        kyc_tier="0",
        account_type="PERSONAL",
        email_verified="false",
        request_id="req-xyz",
        ts="1750000000",
    ).hex()
    assert sig2 == "a5eeeff2a20d4b9b81bfea9a935f0c4eeae18b82a988d3e2fea46459e470ba33", (
        "Python signature must match the Go signer byte-for-byte (vector 2)"
    )


# --- nonce / replay (real Redis via testcontainers) --------------------------


@pytest.fixture
def redis_url() -> cabc.Iterator[str]:
    """Spin a real Redis container; skip (not pass) when Docker is unavailable."""
    docker = pytest.importorskip(
        "docker", reason="docker SDK not installed — skipping Redis replay tests"
    )
    try:
        from testcontainers.redis import RedisContainer
    except ImportError:  # pragma: no cover
        pytest.skip("testcontainers[redis] not installed")

    try:
        docker.from_env().ping()
    except Exception as exc:  # noqa: BLE001
        pytest.skip(f"Docker daemon unavailable: {exc}")

    with RedisContainer("redis:7-alpine") as container:
        host = container.get_container_host_ip()
        port = container.get_exposed_port(6379)
        yield f"redis://{host}:{port}/0"


def test_replay_same_request_id_rejected(monkeypatch: pytest.MonkeyPatch, redis_url: str) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET, nonce_redis_url=redis_url)

    # Same request_id reused → first passes (fresh nonce), second is replay → 401.
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now, request_id="replay-rid-1")
    first = client.get("/protected", headers=headers)
    assert first.status_code == 200, "first signed request with fresh nonce must pass"

    second = client.get("/protected", headers=headers)
    assert second.status_code == 401, "second request with same rid must be 401 (replay)"


def test_distinct_request_ids_both_pass(monkeypatch: pytest.MonkeyPatch, redis_url: str) -> None:
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET, nonce_redis_url=redis_url)

    h1 = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now, request_id="rid-unique-a")
    h2 = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now, request_id="rid-unique-b")
    assert client.get("/protected", headers=h1).status_code == 200
    assert client.get("/protected", headers=h2).status_code == 200, (
        "distinct request-ids must both pass (independent nonces)"
    )


def test_missing_request_id_with_redis_rejected(
    monkeypatch: pytest.MonkeyPatch, redis_url: str
) -> None:
    # Signed request with no X-Request-ID while Redis is configured → 401
    # (cannot replay-check safely). Mirrors the Go verifier's empty-rid path.
    now = int(time.time())
    client = _build_client(monkeypatch, secret=TEST_SECRET, nonce_redis_url=redis_url)
    headers = _signed_headers(TEST_SECRET, "GET", "/protected", b"", now, request_id="")
    resp = client.get("/protected", headers=headers)
    assert resp.status_code == 401, "missing request-id with Redis configured must be 401"
